---
- hosts: 127.0.0.1
  connection: local

  vars:
    cig_sdk_user_files: "{{ansible_env.HOME}}/.cig-sdk"

    # This is alias for localhost loopback so that containers can connect to software running in osx ports
    cig_sdk_docker_host_ip: 10.254.254.254

  tasks:
    - name: Get cig_sdk_dir path
      debug:
        msg: "CIG_SDK_DIR set to '{{cig_sdk_dir}}'"

    # Check if Docker is installed
    - name: Check if Docker is installed
      shell: command -v docker >/dev/null 2>&1
      register: docker_installed
      ignore_errors: yes

    # Install Docker if not found
    - name: Install Docker for Mac
      homebrew_cask:
        name: docker
        state: present
      when: docker_installed.rc != 0

    # Check if Python is installed
    - name: Check that Python 3 is installed
      shell: command -v python3 >/dev/null 2>&1
      register: python_installed
      ignore_errors: yes

      # stat:
      #   path: /usr/local/bin/python3
      # register: python_installed      
    # Install Python if not found
    - name: Install python
      homebrew:
        name: python
        state: present
      when: python_installed.rc != 0

    # Check if PIP is installed
    - name: Check that pip is installed
      shell: command -v pip >/dev/null 2>&1
      register: pip_installed
      ignore_errors: yes

    # Install PIP if not found
    - name: Install pip
      command: "python3 -m pip install --upgrade pip"
      become: yes
      when: pip_installed.rc != 0
  
    # Note: Not needed on brew version
    # Directory permissions
    # - name: Check cig-sdk directory permissions
    #   file:
    #     path: "{{cig_sdk_dir}}"
    #     state: directory
    #     owner: "{{ansible_env.USER}}"
    #     group: "staff"
    #     recurse: yes
    #     mode: 0755
    #   # If this was somehow root owned make sure it's not anymore
    #   become: yes
    #
    - name: Create cig-sdk directories
      file:
        path: "{{ansible_env.HOME}}/.cig-sdk"
        state: directory
        owner: "{{ansible_env.USER}}"
        group: "staff"
        recurse: yes
        mode: 0755
      # If this was somehow root owned make sure it's not anymore
      become: yes
    # Note: Not needed on brew version
    # - name: Symlink cig-sdk bin to PATH
    #   file:
    #     src: "{{cig_sdk_dir}}/bin/cig-sdk"
    #     dest: /usr/local/bin/cig-sdk
    #     state: link
    #   tags: ["pre-install"]
    - name: Check that host ip looback is running
      command: "ifconfig lo0 alias {{ cig_sdk_docker_host_ip }}"
      become: yes
    - name: Ensure host ip looback after reboots
      template:
        src: templates/com.cig_sdk.docker_ip_alias.plist.j2
        dest: /Library/LaunchDaemons/com.cig_sdk.docker_loopback_alias.plist
        owner: root
        group: wheel
        mode: 0644
      become: yes
    - name: Add localunixsocket.local hostname in /etc/hosts
      blockinfile:
        dest: /etc/hosts
        marker: "# {mark}: cig-sdk prevent docker for OSX from slowing in certain networks"
        block: |
          127.0.0.1 localunixsocket
          127.0.0.1 localunixsocket.lan
          127.0.0.1 localunixsocket.local
          127.0.0.1	host.docker.internal
      tags: ["hosts"]
      become: yes
    - name: Start docker for mac
      command: "open -a docker"
    - name: "Check that we have /var/run/docker.sock socket"
      wait_for:
        path: /var/run/docker.sock
        state: present
        timeout: 20
    - name: "Check that we have /var/run/docker.sock socket"
      stat:
        path: /var/run/docker.sock
      register: docker_socket
    - name: Fail if no docker.sock
      fail:
        msg: "Check that Docker for Mac is enabled! /var/run/docker.sock is not mounted. :("
      when: not docker_socket.stat.exists

    - name: Shutdown local Apache server
      command: "command -v apachectl && apachectl stop"
      become: yes
      become_method: sudo
      ignore_errors: yes

    - name: "Uninstall DNSMasq if running locally"
      homebrew:
        name: dnsmasq
        state: uninstalled
      tags: ["dns"]

    - name: Stop previously running cig-sdk services
      command: "docker-compose -f {{cig_sdk_dir}}/docker/services.yml -p cig down"
      environment:
        BOX_IP: "{{cig_sdk_docker_host_ip}}"

    # Required ports are: 80, 443, 53, 25
    - name: Check if required ports are available
      shell: 'lsof -PiTCP -sTCP:LISTEN | grep -E '':(25|53|80|443)\s'' | awk ''{split($9,p,":"); print $1" (port "p[2]")";}'' | sort | uniq'
      register: check_ports

    - fail:
        msg: |
          Required port is in use:
          {{ check_ports.stdout }}
      when: check_ports.stdout != ""

    - name: Start cig-sdk services
      command: "docker-compose -f {{cig_sdk_dir}}/docker/services.yml -p cig up -d --build --force-recreate"
      environment:
        BOX_IP: "{{cig_sdk_docker_host_ip}}"

    - name: Wait for signaler to create CA file
      wait_for:
        path: "{{ cig_sdk_user_files }}/ca/ca.crt"
        state: present
        timeout: 60

    # This only works in OS X and doesn't affect firefox
    # We want to use https locally and you only use ca.key which is generated to you
    - name: Trust self-generated signaler Root certificate in keychain (Mac will open password prompt)
      shell: "security add-trusted-cert -d -r trustRoot -k '/Library/Keychains/System.keychain' ca.crt"
      args:
        chdir: "{{ cig_sdk_user_files }}/ca/"
      become: yes
      become_method: sudo

    - name: Create resolver directory
      file:
        path: /etc/resolver
        state: directory
        mode: 0755
      become: yes
      become_method: sudo
      tags: ["dns"]

    - name: Delete resolver files to trigger dns change
      file:
        path: "/etc/resolver/{{item.domain}}"
        state: absent
      become: yes
      become_method: sudo
      with_items:
        - { ip: "{{ cig_sdk_docker_host_ip }}", domain: test }
      tags: ["dns"]

    - name: Create dns resolver files at /etc/resolver/
      template:
        src: "templates/resolver-dev.conf.j2"
        dest: "/etc/resolver/{{item.domain}}"
        force: yes
      become: yes
      become_method: sudo
      with_items:
        - { ip: "{{ cig_sdk_docker_host_ip }}", domain: test }
      tags: ["dns"]

    # Check if Google Cloud SDK is installed
    - name: Check if Google Cloud SDK is installed
      shell: command -v gcloud >/dev/null 2>&1
      register: gcloud_installed
      ignore_errors: yes
      tags: ["gcloud"]

    # Install Google Cloud SDK if not found
    - name: Install Google Cloud SDK for Mac
      homebrew_cask:
        name: google-cloud-sdk
        state: present
      when: gcloud_installed.rc != 0
      tags: ["gcloud"]

    # Add default config file if not present
    - name: Create config file at {{cig_sdk_user_files}}/config
      template:
        src: "templates/config.j2"
        dest: "{{cig_sdk_user_files}}/config"
        # Do not overwrite existing config
        force: no
      tags: ["config"]

    - name: Install Kustomize
      homebrew:
        name: kustomize
        state: present
